---
title: "hw5"
author: "Baode Gao"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(patchwork)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Problem 2

creat df and tidy it.
```{r warning=FALSE, message=FALSE}
path = 'hw5_data/data/'
file = list.files(path)

p2_df = 
  purrr::map(str_c(path,file), read_csv) %>%
  bind_rows() %>%
  mutate(file_name = gsub(".csv", "", file)
         )

tidy_df = p2_df  %>% 
  separate(file_name, into = c('arm','ID'),sep = '_') %>%
  mutate(ID = as.integer(ID)) %>%
  pivot_longer(week_1:week_8, 
               names_to = "week",
               values_to = "value",
               names_prefix = 'week_') %>%
  mutate(week = as.factor(week)) %>%
  relocate(ID)

knitr::kable(tidy_df[1:10,])
```

visualizaiton
```{r}
tidy_df %>% 
  ggplot(aes(x = week, y = value, group = paste0(ID, arm), color = arm)) +
  geom_line() 
  
```

With the increase of time, the control group fluctuated little up and down. The value of the experimental group showed an upward trend by comparison. 

## Problem 3

import data
```{r}
library(tidyverse)

set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))
```

replace missing values
```{r}
replace_missing = function(x) {

  col_vals = x
  
  if (class(col_vals) == 'numeric') {
    col_vals = ifelse(is.na(col_vals), mean(col_vals, na.rm = TRUE), col_vals)
  } 
  
  else if (class(col_vals) == 'character') {
    col_vals = ifelse(is.na(col_vals), "virginica", col_vals)
  }
  
  return(col_vals)
  
}


iris_without_missing = 
  iris_with_missing %>% map_df(replace_missing)
  

print(sum(is.na(iris_without_missing)))

knitr::kable(head(iris_without_missing,13))
```



